//
//  SearchCitiesInteractor.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import ObjectMapper

protocol SearchCitiesBusinessLogic {
    func fetchCities(request: SearchCitiesModel.Request)
}

class SearchCitiesInteractor: SearchCitiesBusinessLogic {
    var presenter: SearchCitiesPresentationLogic?
    var worker: SearchCitiesWorker?
    
    func fetchCities(request: SearchCitiesModel.Request) {
        worker = SearchCitiesWorker(searchCitiesStore: SearchCitiesAPIStore())
        let parameter = Mapper().toJSON(request)
        worker?.fetchCities(parameter: parameter, completion: { (response) in
            self.presenter?.presentCities(response: response)
        })
    }
}
