//
//  SearchCitiesWorker.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Alamofire
import CoreData

typealias searchCitiesAPIResponse = (_ response: SearchCitiesModel.Response) -> Void

protocol SearchCitiesStoreProtocol: class {
    func fetchCities(parameter: [String: Any], completion: @escaping (searchCitiesAPIResponse))
}

class SearchCitiesWorker {
    
    var searchCitiesStore: SearchCitiesStoreProtocol
    
    init(searchCitiesStore: SearchCitiesStoreProtocol) {
        self.searchCitiesStore = searchCitiesStore
    }

    func fetchCities(parameter: [String: Any], completion: @escaping (searchCitiesAPIResponse)) {
        self.searchCitiesStore.fetchCities(parameter: parameter) { (response) in
            completion(response)
        }
    }
}
