//
//  SearchCitiesPresenter.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchCitiesPresentationLogic {
    func presentCities(response: SearchCitiesModel.Response)
}

class SearchCitiesPresenter: SearchCitiesPresentationLogic {
    weak var viewController: SearchCitiesDisplayLogic?
    
    func presentCities(response: SearchCitiesModel.Response) {
        viewController?.displayCities(response: response)
    }
}
