//
//  SearchCitiesRouter.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchCitiesRoutingLogic {
    func navigateToSomewhere(source: SearchCitiesViewController, destination: UIViewController)
}

class SearchCitiesRouter: NSObject, SearchCitiesRoutingLogic {
    weak var viewController: SearchCitiesViewController?
    
    // MARK: Navigation
    func navigateToSomewhere(source: SearchCitiesViewController, destination: UIViewController) {
        
    }
}
