//
//  DisplayDashboardPresenter.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayDashboardPresentationLogic {
    func presentSomething(response: DisplayDashboardModel.Response)
}

class DisplayDashboardPresenter: DisplayDashboardPresentationLogic {
    weak var viewController: DisplayDashboardDisplayLogic?
    
    // MARK: Do something
    func presentSomething(response: DisplayDashboardModel.Response) {
        let viewModel = DisplayDashboardModel.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
