//
//  DisplayDashboardRouter.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DisplayDashboardRoutingLogic {
    func navigateToSomewhere(source: DisplayDashboardViewController, destination: UIViewController, isPresented: Bool)
}

class DisplayDashboardRouter: NSObject, DisplayDashboardRoutingLogic {
    weak var viewController: DisplayDashboardViewController?
    
    // MARK: Navigation
    func navigateToSomewhere(source: DisplayDashboardViewController, destination: UIViewController, isPresented: Bool) {
        if isPresented {
            let navigationController = UINavigationController(rootViewController: destination)
            source.present(navigationController, animated: true, completion: nil)
        } else {
            source.show(destination, sender: nil)
        }
    }
}
