//
//  DisplayDashboardInteractor.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayDashboardBusinessLogic {
    func doSomething(request: DisplayDashboardModel.Request)
}

protocol DisplayDashboardDataStore {
    //var name: String { get set }
}

class DisplayDashboardInteractor: DisplayDashboardBusinessLogic, DisplayDashboardDataStore {
    var presenter: DisplayDashboardPresentationLogic?
    var worker: DisplayDashboardWorker?
    //var name: String = ""
    
    // MARK: Do something
    func doSomething(request: DisplayDashboardModel.Request) {
        worker = DisplayDashboardWorker()
        worker?.doSomeWork()
        
        let response = DisplayDashboardModel.Response()
        presenter?.presentSomething(response: response)
    }
}
