//
//  DisplayDashboardModels.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct DisplayDashboardModel {
    
    // MARK: Object model for API requests
    struct Request {
        
    }
    
    // MARK: Object model for API responses
    struct Response {
        
    }
    
    // MARK: Object model for UI rendering
    struct ViewModel {
        
    }
}
