//
//  DisplayDashboardView.swift
//  Lemi-App
//
//  Created by Xander Mercado on 3/19/20.
//  Copyright (c) 2020 Xander Mercado. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DisplayDashboardViewProtocol: class {
    
}

class DisplayDashboardView: UIView {
    weak var delegate: DisplayDashboardViewProtocol?
    var viewModel = DisplayDashboardModel.ViewModel()

    private func setupView() {
        
    }
    
    private func setupGesture() {
        
    }
    
    @objc func hideKeyboard() {
        self.endEditing(true)
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupView()
        setupGesture()
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}
